[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 12
# size = 4

[window]
opacity = 0.6
blur = true
decorations = "Buttonless"
padding = { x = 6, y = 6 }

[mouse]
hide_when_typing = false

[scrolling]
history = 100000

[terminal]
